#!/usr/bin/env bash
# Build writing/sources/chNN.md — one file per chapter, holding the PR title/date/body and every
# commit subject+body for that chapter's PRs. Run once from the repo root; re-run only if the
# history changes. Reads GitHub via `gh`; nothing else in writing/ should need to.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
out=writing/sources
mkdir -p "$out"

# chapter -> PR numbers (see writing/outline.md)
declare -a CH_PRS=(
  ""                     # index 0 unused
  "1 2 3 4"              # ch01
  "5 6"                  # ch02
  "8 9 10 11 12 13"      # ch03
  "14 15"                # ch04
  "16 17"                # ch05
  "18 19 20"             # ch06
  "21 22"                # ch07
  "23 24 25"             # ch08
  "26 27 28 29 30 31"    # ch09
  "32 33 34 35 36"       # ch10
  "37 38 39"             # ch11
  "40 41"                # ch12
)

emit_pr() {
  local n=$1
  gh pr view "$n" --json number,title,mergedAt,additions,deletions,body,commits \
    --jq '"## PR #\(.number) — \(.title)\n*merged \(.mergedAt[:10]) · +\(.additions)/−\(.deletions)*\n\n### PR body\n\n\(if .body == "" then "_(empty)_" else .body end)\n\n### Commits\n" + ([.commits[] | "- **\(.messageHeadline)**" + (if .messageBody == "" then "" else "\n\n" + (.messageBody | split("\n") | map("  " + .) | join("\n")) end)] | join("\n\n"))'
}

for ch in $(seq 1 12); do
  f=$(printf "%s/ch%02d.md" "$out" "$ch")
  printf "# Sources — chapter %02d\n\nPRs: %s. Generated by writing/tools/build_sources.sh on %s.\n\n" \
    "$ch" "$(echo ${CH_PRS[$ch]} | sed 's/ /, #/g; s/^/#/')" "$(date +%F)" > "$f"
  if [ "$ch" = 1 ]; then
    {
      echo "## Pre-PR commits (before #1)"
      echo
      # commits from the root up to (not including) the first PR merge
      first_merge=$(git rev-list --merges HEAD | tail -1)   # tail, not head: no SIGPIPE under pipefail
      git log --reverse --format='- **%s** (%h, %ad)%n%n%w(0,2,2)%b' --date=short "${first_merge}^1" -- \
        | sed '/^  $/d'
      echo
    } >> "$f"
  fi
  for n in ${CH_PRS[$ch]}; do
    emit_pr "$n" >> "$f"
    printf "\n\n" >> "$f"
  done
  echo "wrote $f ($(wc -w < "$f") words)"
done
